FROM python:3.7-buster
LABEL com.dainesanalytics.pythonml.version=v2.6
EXPOSE 8080
RUN pip install numpy scipy matplotlib ipython sympy pandas scikit-learn jupyterlab pandas-datareader seaborn
RUN pip install PyMySQL imbalanced-learn xgboost statsmodels pmdarima netCDF4
RUN pip install lxml html5lib requests beautifulsoup4 selenium python-dotenv
RUN pip install pillow tensorflow
RUN pip install pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN useradd -m -d /home/pythonml -s /bin/bash pythonml
RUN mkdir /home/pythonml/.ssh && chown pythonml:pythonml /home/pythonml/.ssh
COPY --chown=pythonml:pythonml id_rsa_docker /home/pythonml/.ssh/id_rsa
RUN chmod 700 /home/pythonml/.ssh/id_rsa
USER pythonml
RUN git config --global user.name "David Lowe" && git config --global user.email david.lowe@dainesanalytics.com
WORKDIR /home/pythonml