FROM python:3.8-buster
LABEL com.dainesanalytics.tensorflowml.version=v1.03
EXPOSE 8080
SHELL ["/bin/bash", "-c"]
RUN useradd -m -d /home/tensorflowml -s /bin/bash tensorflowml && \
    mkdir /home/tensorflowml/.ssh && \
    chown tensorflowml:tensorflowml /home/tensorflowml/.ssh
COPY --chown=tensorflowml:tensorflowml id_rsa_docker /home/tensorflowml/.ssh/id_rsa
RUN chmod 700 /home/tensorflowml/.ssh/id_rsa
USER tensorflowml
RUN git config --global user.name "David Lowe" && \
    git config --global user.email david.lowe@dainesanalytics.com
WORKDIR /home/tensorflowml
RUN python -m venv appdev && \
    source appdev/bin/activate && \
    python -m pip install --upgrade pip && \
    python -m pip install numpy scipy matplotlib ipython pandas scikit-learn seaborn && \
    python -m pip install jupyterlab nltk gensim python-dotenv boto3 && \
    python -m pip install tensorflow tensorflow-addons tensorflow-data-validation apache-beam
