FROM ubuntu:bionic
LABEL com.dainesanalytics.webscrape.version=v1.1
EXPOSE 8080
RUN apt update
RUN apt install -y python3 python3-pip wget git firefox
RUN pip3 install pandas jupyterlab PyMySQL lxml html5lib requests beautifulsoup4 selenium python-dotenv boto3
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
RUN tar -xvzf geckodriver-v0.27.0-linux64.tar.gz
RUN cp geckodriver /usr/local/bin
# RUN chmod +x /usr/local/bin/geckodriver
RUN useradd -m -d /home/webscrape -s /bin/bash webscrape
RUN mkdir /home/webscrape/.ssh && chown webscrape:webscrape /home/webscrape/.ssh
COPY --chown=webscrape:webscrape id_rsa_docker /home/webscrape/.ssh/id_rsa
RUN chmod 700 /home/webscrape/.ssh/id_rsa
USER webscrape
RUN git config --global user.name "David Lowe" && git config --global user.email david.lowe@dainesanalytics.com
WORKDIR /home/webscrape