FROM continuumio/anaconda3:latest
LABEL com.dainesanalytics.quantfin.version=v1.2
EXPOSE 8080
# RUN /opt/conda/bin/conda update -y anaconda
RUN /opt/conda/bin/pip install yfinance quandl alpha_vantage edgar
RUN /opt/conda/bin/conda install -y PyMySQL selenium pandas-datareader
RUN useradd -m -d /home/quantfin -s /bin/bash quantfin
RUN mkdir /home/quantfin/.ssh && chown quantfin:quantfin /home/quantfin/.ssh
COPY --chown=quantfin:quantfin id_rsa_docker /home/quantfin/.ssh/id_rsa
RUN chmod 700 /home/quantfin/.ssh/id_rsa
USER quantfin
RUN git config --global user.name "David Lowe" && git config --global user.email david.lowe@dainesanalytics.com
WORKDIR /home/quantfin