FROM rocker/verse:latest
LABEL com.dainesanalytics.rstudio.version=v1.0
RUN Rscript -e "install.packages(c('knitr', 'tidyverse', 'caret', 'corrplot', 'mailR', 'DMwR', 'ROCR', 'Hmisc', 'randomForest', 'e1071', 'elasticnet', 'gbm', 'xgboost'))"
RUN mkdir /home/rstudio/.ssh && chown rstudio:rstudio /home/rstudio/.ssh
COPY --chown=rstudio:rstudio id_rsa /home/rstudio/.ssh
COPY --chown=rstudio:rstudio .Renviron /home/rstudio
RUN git config --global user.name "David Lowe" && git config --global user.email david.lowe@dainesanalytics.com