FROM python:3.8-buster
LABEL com.dainesanalytics.pythonml.version=v2.12
EXPOSE 8080
RUN python3 -m pip install numpy scipy matplotlib ipython sympy pandas scikit-learn jupyterlab seaborn nltk gensim
RUN python3 -m pip install PyMySQL imbalanced-learn xgboost python-dotenv boto3
RUN useradd -m -d /home/pythonml -s /bin/bash pythonml
RUN mkdir /home/pythonml/.ssh && chown pythonml:pythonml /home/pythonml/.ssh
COPY --chown=pythonml:pythonml id_rsa_docker /home/pythonml/.ssh/id_rsa
RUN chmod 700 /home/pythonml/.ssh/id_rsa
USER pythonml
RUN git config --global user.name "David Lowe" && git config --global user.email david.lowe@dainesanalytics.com
WORKDIR /home/pythonml